# GitHub Actions CI/CD Pipeline for ToDo App
# This workflow automatically deploys the app to GitHub Pages on every push to main

name: Deploy ToDo App to GitHub Pages

# Trigger the workflow
on:
  # Run on pushes to main branch
  push:
    branches: [ main ]
  
  # Allow manual triggering from GitHub UI
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and validation job
  build:
    name: Build and Validate
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Validate HTML files
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
          css: true
          
      # Check for common JavaScript errors
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      # Install a simple JavaScript linter
      - name: Install dependencies
        run: |
          npm init -y
          npm install --save-dev jshint
          
      # Run JavaScript validation
      - name: Lint JavaScript
        run: |
          npx jshint script.js --config '{
            "esversion": 6,
            "browser": true,
            "undef": true,
            "unused": true,
            "predef": ["localStorage", "confirm"]
          }'
          
      # Verify all required files exist
      - name: Verify files exist
        run: |
          echo "Checking required files..."
          test -f index.html && echo "✓ index.html found"
          test -f style.css && echo "✓ style.css found"
          test -f script.js && echo "✓ script.js found"
          echo "All required files present!"
          
      # Test that the HTML file has required elements
      - name: Basic functionality test
        run: |
          echo "Running basic structure tests..."
          grep -q 'id="taskInput"' index.html && echo "✓ Task input found"
          grep -q 'id="tasksList"' index.html && echo "✓ Tasks list found"
          grep -q 'id="addTaskForm"' index.html && echo "✓ Add form found"
          grep -q 'class="delete-button"' style.css && echo "✓ Delete button styles found"
          echo "Basic structure tests passed!"

  # Deployment job
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build  # Only deploy if build job succeeds
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Setup Pages configuration
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # Create deployment artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Upload entire repository (since it's a static site)
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      # Post-deployment verification
      - name: Verify deployment
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "📱 Your ToDo app is now live at: ${{ steps.deployment.outputs.page_url }}"
          echo "⏱️ Deployment typically takes 1-2 minutes to be fully available"